<?php

namespace ContainerBAN5Awt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NetcIawService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NetcIaw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NetcIaw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dossiersMedicaux' => ['privates', '.errored..service_locator.NetcIaw.App\\Entity\\DossiersMedicaux', NULL, 'Cannot autowire service ".service_locator.NetcIaw": it needs an instance of "App\\Entity\\DossiersMedicaux" but this type has been excluded in "config/services.yaml".'],
        ], [
            'dossiersMedicaux' => 'App\\Entity\\DossiersMedicaux',
        ]);
    }
}
