<?php

namespace ContainerBAN5Awt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uouj27XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uouj27X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uouj27X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'consultationRepository' => ['privates', 'App\\Repository\\ConsultationRepository', 'getConsultationRepositoryService', true],
        ], [
            'consultationRepository' => 'App\\Repository\\ConsultationRepository',
        ]);
    }
}
