<?php

namespace ContainerBAN5Awt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocteur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Knil6rm.App\Entity\Docteur' shared service.
     *
     * @return \App\Entity\Docteur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Knil6rm": it needs an instance of "App\\Entity\\Docteur" but this type has been excluded in "config/services.yaml".');
    }
}
