<?php

namespace ContainerPm1yEOG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AcvlFyNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AcvlFyN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AcvlFyN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dossiersMedicaux' => ['privates', '.errored..service_locator.AcvlFyN.App\\Entity\\DossiersMedicaux', NULL, 'Cannot autowire service ".service_locator.AcvlFyN": it needs an instance of "App\\Entity\\DossiersMedicaux" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dossiersMedicaux' => 'App\\Entity\\DossiersMedicaux',
            'entityManager' => '?',
        ]);
    }
}
