<?php

namespace ContainerPm1yEOG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5MvA8BYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5MvA8BY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5MvA8BY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'docteur' => ['privates', '.errored..service_locator.5MvA8BY.App\\Entity\\Docteur', NULL, 'Cannot autowire service ".service_locator.5MvA8BY": it needs an instance of "App\\Entity\\Docteur" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'docteur' => 'App\\Entity\\Docteur',
            'entityManager' => '?',
        ]);
    }
}
