<?php

namespace ContainerPm1yEOG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XLD_TihService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xLD.Tih' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xLD.Tih'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'consultation' => ['privates', '.errored..service_locator.xLD.Tih.App\\Entity\\Consultation', NULL, 'Cannot autowire service ".service_locator.xLD.Tih": it needs an instance of "App\\Entity\\Consultation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'consultation' => 'App\\Entity\\Consultation',
        ]);
    }
}
