<?php

namespace ContainerPm1yEOG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossiersMedicauxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AcvlFyN.App\Entity\DossiersMedicaux' shared service.
     *
     * @return \App\Entity\DossiersMedicaux
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AcvlFyN": it needs an instance of "App\\Entity\\DossiersMedicaux" but this type has been excluded in "config/services.yaml".');
    }
}
