<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPm1yEOG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPm1yEOG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPm1yEOG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPm1yEOG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPm1yEOG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pm1yEOG',
    'container.build_id' => '05218c27',
    'container.build_time' => 1740000146,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPm1yEOG');
